{
    "po_header": {
        "id": 1,
        "po_number": "1006",
        "po_type": "STANDARD",
        "po_status": "APPROVED",
        "supplier_name": "RIZ & CO",
        "location": "Shenoy Nagar",
        "ship_to": "CHENNAI",
        "bill_to": "CHENNAI",
        "buyer_name": "SHAR,",
        "total_amount": null,
        "status": null,
        "approve": true
    },
    "po_lineitems": [
        {
            "id": 1,
            "item_name": "SHAR_SERVICE",
            "line_num": "1",
            "quantity": "20",
            "unit_price": "200",
            "amount_billed": null,
            "order_type_lookup_code": "QUANTITY",
            "purchase_basis": "GOODS",
            "category_name": "General.General",
            "closed_code": "OPEN",
            "item_description": null,
            "need_by_date": null,
            "promised_date": null,
            "header": 1
        },
        {
            "id": 2,
            "item_name": "SHAR_FG",
            "line_num": "2",
            "quantity": "20",
            "unit_price": "100",
            "amount_billed": null,
            "order_type_lookup_code": "QUANTITY",
            "purchase_basis": "GOODS",
            "category_name": "General.General",
            "closed_code": "OPEN",
            "item_description": null,
            "need_by_date": null,
            "promised_date": null,
            "header": 1
        },
        {
            "id": 15,
            "item_name": "SHAR_SERVICE",
            "line_num": "1",
            "quantity": "20",
            "unit_price": "200",
            "amount_billed": null,
            "order_type_lookup_code": "QUANTITY",
            "purchase_basis": "GOODS",
            "category_name": "General.General",
            "closed_code": "OPEN",
            "item_description": null,
            "need_by_date": null,
            "promised_date": null,
            "header": 1
        },
        {
            "id": 16,
            "item_name": "SHAR_FG",
            "line_num": "2",
            "quantity": "20",
            "unit_price": "100",
            "amount_billed": null,
            "order_type_lookup_code": "QUANTITY",
            "purchase_basis": "GOODS",
            "category_name": "General.General",
            "closed_code": "OPEN",
            "item_description": null,
            "need_by_date": null,
            "promised_date": null,
            "header": 1
        },
        {
            "id": 17,
            "item_name": "SHAR_SERVICE",
            "line_num": "1",
            "quantity": "20",
            "unit_price": "200",
            "amount_billed": null,
            "order_type_lookup_code": "QUANTITY",
            "purchase_basis": "GOODS",
            "category_name": "General.General",
            "closed_code": "OPEN",
            "item_description": null,
            "need_by_date": null,
            "promised_date": null,
            "header": 1
        },
        {
            "id": 18,
            "item_name": "SHAR_FG",
            "line_num": "2",
            "quantity": "20",
            "unit_price": "100",
            "amount_billed": null,
            "order_type_lookup_code": "QUANTITY",
            "purchase_basis": "GOODS",
            "category_name": "General.General",
            "closed_code": "OPEN",
            "item_description": null,
            "need_by_date": null,
            "promised_date": null,
            "header": 1
        }
    ],
    "invoice_info": {
        "id": 1,
        "VendorAddress": {
            "id": 8,
            "house_number": null,
            "po_box": null,
            "road": null,
            "city": "Chennai",
            "state": null,
            "postal_code": "600018",
            "country_region": "India",
            "street_address": "B 3 Vasanth Apartment\nNo 40",
            "unit": null,
            "city_district": null,
            "suburb": null,
            "house": null,
            "level": null,
            "state_district": null
        },
        "CustomerAddress": null,
        "BillingAddress": {
            "id": 9,
            "house_number": null,
            "po_box": null,
            "road": null,
            "city": "Chennai",
            "state": null,
            "postal_code": "600040",
            "country_region": "India",
            "street_address": "Y Block, 4th Street, Anna Nagar No. 83",
            "unit": null,
            "city_district": null,
            "suburb": null,
            "house": null,
            "level": null,
            "state_district": null
        },
        "ShippingAddress": {
            "id": 10,
            "house_number": null,
            "po_box": null,
            "road": null,
            "city": "Chennai",
            "state": null,
            "postal_code": "600040",
            "country_region": "India",
            "street_address": "Y Block, 4th Street, Anna Nagar No. 83",
            "unit": null,
            "city_district": null,
            "suburb": null,
            "house": null,
            "level": null,
            "state_district": null
        },
        "items": [
            {
                "id": 1,
                "Description": "HP ProBook 440 G9",
                "Quantity": "5.0",
                "Unit": "NOS",
                "UnitPrice": "63500.0",
                "ProductCode": "8471",
                "Amount": "317500.0",
                "SubTotal": null,
                "TotalTax": null,
                "Date": null,
                "Tax": null,
                "PreviousUnpaidBalance": null,
                "AmountDue": null,
                "ServiceStartDate": null,
                "ServiceEndDate": null,
                "ServiceAddressRecipient": null,
                "RemittanceAddressRecipient": null,
                "invoice": 1,
                "ServiceAddrress": null,
                "RemittanceAddress": null
            }
        ],
        "VendorName": "Phalgune Infotech Private Limited",
        "VendorAddressRecipient": "Phalgune Infotech Private Limited",
        "CustomerName": "Focusr Consultancy and Technology Private Limited",
        "CustomerAddressRecipient": null,
        "CustomerId": null,
        "InvoiceId": "PIPL/260/2023-24",
        "InvoiceDate": "2023-09-30",
        "InvoiceTotal": "374650.0",
        "BillingAddressRecipient": "Focusr Consultancy and Technology Private Limited",
        "ShippingAddressRecipient": "Focusr Consultancy and Technology Private Limited",
        "DueDate": null,
        "PurchaseOrder": null,
        "po_header": 1
    }
}